[profile.default]
solc = "0.8.22"
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
evm_version = 'london'
#OpenZeppelin foundry upgrades
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "./out"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
